[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"
[build.environment]
  NODE_VERSION = "12"
  YARN_VERSION = "1.22.4"
  YARN_FLAGS = "--no-ignore-optional"

[[plugins]]
  package = "./plugins/set-env-by-context"

  [[redirects]]
  from = "/payment/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
