logo: /img/logo-beke-horizontal.png
rightitems:
  - logo: /img/icono-tarifa-flex.svg
    title: Tarifa flex
    url: "#tarifa-flex"
  - logo: /img/instagram.svg
    url: https://www.instagram.com/bekehotels/
  - logo: /img/facebook.svg
    url: https://www.facebook.com/BekeHotels
